import type { Metadata } from "next";
import {
  proximaBold,
  proximaExtraBold,
  sourceSansRegular,
  baradigBold,
} from "./styles/fonts";

import "./styles/globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${proximaBold.variable} 
          ${proximaExtraBold.variable} 
          ${sourceSansRegular.variable} 
          ${baradigBold.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
